name: build apps

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - apps/**
jobs:
  push:
    name: "apps:${{ matrix.app }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - opus
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: setup buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug

      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: ./apps/${{ matrix.app }}
          file: ./apps/${{ matrix.app }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/hexiahost/apps:${{ matrix.app }}
