name: build games

on:
  push:
    branches:
      - master
    paths:
      - games/**
jobs:
  push:
    name: "games:${{ matrix.game.name }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game:
          - {name: "tes3mp", platform: "linux/amd64,linux/arm64"}
          - {name: "valheimplus", platform: "linux/amd64"}
          - {name: "byond", platform: "linux/amd64"}
          - {name: "starbound", platform: "linux/amd64"}
          - {name: "source", platform: "linux/amd64"}
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: setup buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug

      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: ./games/${{ matrix.game.name }}
          file: ./games/${{ matrix.game.name }}/Dockerfile
          platforms: ${{ matrix.game.platform }}
          push: true
          tags: |
            ghcr.io/hexiahost/games:${{ matrix.game.name }}
